-- Drop existing tables if they exist to ensure re-execution does not fail
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE UserRoles CASCADE CONSTRAINTS;
DROP TABLE Doctor CASCADE CONSTRAINTS;
DROP TABLE Patient CASCADE CONSTRAINTS;
DROP TABLE Appointment CASCADE CONSTRAINTS;
DROP TABLE Visit CASCADE CONSTRAINTS;
DROP TABLE MedicalRecord CASCADE CONSTRAINTS;
DROP TABLE TreatmentHistory CASCADE CONSTRAINTS;
DROP TABLE Prescription CASCADE CONSTRAINTS;
DROP TABLE Billing CASCADE CONSTRAINTS;

-- UserRoles Table
CREATE TABLE UserRoles (
    RoleID VARCHAR2(50) PRIMARY KEY,
    RoleName VARCHAR2(50) CHECK (RoleName IN ('Admin', 'Doctor', 'BillingStaff'))
);


-- Users Table
CREATE TABLE Users (
    UserID VARCHAR2(50) PRIMARY KEY,
    Username VARCHAR2(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR2(256) NOT NULL,
    RoleID VARCHAR2(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Users_Role FOREIGN KEY (RoleID) REFERENCES UserRoles(RoleID)
);